name: pet_adoption_app
description: A Flutter app for pet adoption with BLoC state management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  provider: ^6.1.1
  
  # Networking
  dio: ^5.4.3
  
  # Logging & Debugging
  talker: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_flutter: ^4.1.3
  
  # Utils
  rxdart: ^0.27.7
  connectivity_plus: ^6.0.3
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Animations
  animations: ^2.0.11
  lottie: ^3.1.2
  confetti: ^0.7.0
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true